### ISSUE TITLE
Docs: Quickstart Guide on Getting Started with Novu Kotlin

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/novu-kotlin#10]
We currently have quickstart guides in different languages.

We need a Kotlin Quickstart. There's a template to follow below:

[Get Started with PHP](https://docs.novu.co/overview/quickstart/get-started-with-php)

**Comment by unicodeveloper** [comment]
@mayorJAY tagging you in case you are interested or know anyone who is. 😉

**Comment by sfxjolugbohunmi** [comment]
I'm guessing it should be done on the main repo https://github.com/novuhq/novu. Is that correct?

**Comment by mayorJAY** [comment]
@unicodeveloper I'm guessing it should be done on the main repo https://github.com/novuhq/novu. Is that correct?

**Comment by unicodeveloper** [comment]
Yes. it will be done in the main repo. We have a docs directory there. These are all the quickstarts we have done currently https://github.com/novuhq/novu/tree/main/docs/docs/overview/quickstart

Is it something you might be interested in?

**Comment by mayorJAY** [comment]
Yes, I'll pick that up

**Comment by unicodeveloper** [comment]
What day will you be able to start? @mayorJAY 

Asking this so I can constantly check in on this for progress and completion. We are hoping to be done with all quickstart guides before July 14.

**Comment by mayorJAY** [comment]
I'll start tomorrow. I intend to write and send the PRs in bits

**Comment by unicodeveloper** [comment]
Alright. Looking forward to it. 

For the docs, clone the repo, `cd` into docs, run `npm install` and run `npm run start` to serve up the docs.

**Comment by mayorJAY** [comment]
https://github.com/novuhq/novu/pull/3720 @unicodeveloper @Cliftonz
