### ISSUE TITLE
Can't seem to trigger notification to a topic

### ISSUE THREAD

**Issue by frankkoornstra** [novuhq/novu-kotlin#3]
Thanks for writing this SDK in Kotlin, it's amazing to see it supported as one of the first languages :heart:

I'm trying to figure out how to send a notification to a topic. In [the docs](https://docs.novu.co/platform/topics#sending-a-notification-to-a-topic) it tells me to do this with the trigger endpoint but [none of the constructor methods](https://github.com/novuhq/novu-kotlin/blob/814edde8faf32ff85b7d3836e698caee96ba2eb5/src/main/kotlin/dto/request/TriggerEventRequest.kt#L21-L54) seems to allow for this input:
```
to: [{ type: 'Topic', topicKey: topicKey }],
```

Am I overlooking something or is this something that still needs to be added?

**Comment by unicodeveloper** [comment]
@nulllvoid @Crashiv Please check this
