### ISSUE TITLE
Add set-integration-as-primary Endpoint

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-kotlin#33]
This feature is not yet implemented in the SDK. Add the implementation and this should include unit test
API reference: https://docs.novu.co/api-reference/integrations/set-integration-as-primary

**Comment by mayorJAY** [comment]
@Cliftonz

**Comment by DeKaN** [comment]
Hi, can I take the issue?

**Comment by unicodeveloper** [comment]
Yes. Assigning you to this now @DeKaN

**Comment by unicodeveloper** [comment]
Assigned! ⭐
