### ISSUE TITLE
README LABELS INCLUSION .

### ISSUE THREAD

**Issue by shelar1423** [novuhq/novu-kotlin#52]
why no labels for this repo readme ?
![image](https://github.com/novuhq/novu-kotlin/assets/82649533/373a15bd-2b92-4193-a198-d0efdb37b11d)
meanwhile all other novu sdk repos have :
![image](https://github.com/novuhq/novu-kotlin/assets/82649533/194d7d45-dbe4-4574-88d9-68776cccf638)

**Comment by mayorJAY** [comment]
You can raise a PR for that, if you don't mind @shelar1423

**Comment by shelar1423** [comment]
Sure @unicodeveloper I'll check with the repo and let you know what labels I'm planning.

**Comment by nabinbhatt** [comment]
Hey @unicodeveloper I want to work on this, can you assign this issue to me?

**Comment by nabinbhatt** [comment]
I will be adding some informative labels like build status, project's version, Kotlin version, etc. please let me know @unicodeveloper

**Comment by nabinbhatt** [comment]
Hello @mayorJAY here's is what I've come up with 
![image](https://github.com/novuhq/novu-kotlin/assets/83168881/d62c76c7-5176-491a-b1a8-6f8ee0bc0e40)
If you like it, please tell me if I can submit a PR
cc: @unicodeveloper

**Comment by shelar1423** [comment]
@nabinbhatt sure ,i don't think I'll be able to work on this current @mayorJAY @unicodeveloper nabin can take up this issue
