### ISSUE TITLE
feature request: add sdk methods for organization apis

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu-kotlin#54]
Take this issue as reference https://github.com/novuhq/novu/issues/4775

**Comment by unicodeveloper** [comment]
@mayorJAY @Basfar

**Comment by mayorJAY** [comment]
Got it

**Comment by mayorJAY** [comment]
@jainpawan21 https://api.novu.co/api#/Organizations/OrganizationController_getOrganizations
I tried sending a request to this endpoint using Postman, but the response body I got seems to be different from what is stated on the Swagger doc. The doc seems to be confusing, this is what I got on Postman:

```{
{
    "data": [
        {
            "_id": String,
            "name": String,
            "createdAt": "2023-06-22T21:01:05.684Z",
            "updatedAt": "2023-06-22T21:01:05.684Z",
            "__v": 0
        }
    ]
}
